import type { Project } from "./projects";
import type { CardData } from "@/components/CaseGrid";

export const PROJECTS_MS: Record<string, Project> = {
  saujana: {
    id: "saujana",
    eyebrow: "Reka & Bina · BINA START",
    title: "Setingkat Saujana",
    location: "Bandar Saujana, Selangor",
    year: "2024",
    hero: "/assets/assets/house 1.jpg",
    lead:
      "Rumah setingkat padat yang ditala untuk keluarga muda Lembah Klang — keluasan efisien, beranda dalam, dan ruang teras pelan terbuka yang tenang.",
    specs: [
      { k: "Pakej", v: "BINA START" },
      { k: "Keluasan binaan", v: "1,200 kps" },
      { k: "Jenis", v: "Setingkat" },
      { k: "Bilik tidur", v: "3 bilik · 2 mandi" },
      { k: "Tempoh", v: "5 bulan" },
      { k: "Harga", v: "dari RM200,000" },
    ],
    plan: {
      img: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1400&q=80&auto=format&fit=crop",
      caption: "Keluasan setingkat · ruang tamu terbuka · beranda menghadap utara",
    },
    intent:
      "Ringkasannya ialah rumah permulaan yang tidak terasa permulaan. Kami menggabungkan ruang tamu, ruang makan dan dapur ke dalam satu volum berterusan, mengalihkan bilik tidur ke tepi belakang yang lebih tenang, dan memperbesar beranda supaya bahagian depan menjadi bilik yang digunakan setiap hari — bukan hanya laluan.",
    materials: ["Konkrit fair-faced off-form", "Fascia papan simen", "Dinding bata dibakar tanah liat", "Aluminium bersalut serbuk", "Siling kayu keras tempatan"],
    gallery: [
      { img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80&auto=format&fit=crop", cap: "Sayap tamu + makan terbuka" },
      { img: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=900&q=80&auto=format&fit=crop", cap: "Skrin beranda waktu senja" },
      { img: "https://images.unsplash.com/photo-1600566753086-00f18fe6ba12?w=900&q=80&auto=format&fit=crop", cap: "Kaunter dapur, cahaya utara" },
    ],
    highlights: [
      { n: "01", t: "Pengudaraan silang", d: "Kesan timbunan melalui louver tinggi mengekalkan dalaman 3–4°C di bawah suhu sekitar." },
      { n: "02", t: "Koridor satu beban", d: "Tiada ruang dewan terbuang — setiap meter boleh didiami." },
      { n: "03", t: "Tingkat kedua masa hadapan", d: "Asas dispek untuk tingkat pertama masa hadapan tanpa retrofit." },
    ],
  },
  subang: {
    id: "subang",
    eyebrow: "Reka & Bina · BINA PLUS",
    title: "Pavilion Subang",
    location: "Subang Jaya, Selangor",
    year: "2024",
    hero: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1800&q=80&auto=format&fit=crop",
    lead:
      "Rumah pavilion separuh-dua-tingkat dibina sekitar halaman taman tengah — ruang tamu cerah di bawah, sayap bilik tidur peribadi di atas.",
    specs: [
      { k: "Pakej", v: "BINA PLUS" },
      { k: "Keluasan binaan", v: "1,500 kps" },
      { k: "Jenis", v: "Separuh dua tingkat" },
      { k: "Bilik tidur", v: "4 bilik · 3 mandi" },
      { k: "Tempoh", v: "6 bulan" },
      { k: "Harga", v: "dari RM350,000" },
    ],
    plan: {
      img: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1400&q=80&auto=format&fit=crop",
      caption: "Pelan dua-zon · tingkat bawah awam · sayap bilik tidur atas",
    },
    intent:
      "Keluarga muda berempat memerlukan cahaya siang tanpa kehilangan privasi dari jalan. Kami membahagikan program merentasi dua aras dan membungkus sisi taman dalam kaca penuh ketinggian, meninggalkan muka jalan sebagai fasad skrin kayu yang tenang.",
    materials: ["Skrin tegak spotted-gum", "Plaster digilap", "Lantai travertine dihalus", "Bingkai tingkap teranodisasi hitam", "Kerja kayu oak putih"],
    gallery: [
      { img: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&q=80&auto=format&fit=crop", cap: "Sayap tamu menghadap halaman taman" },
      { img: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&q=80&auto=format&fit=crop", cap: "Lubang tangga, cahaya atas" },
      { img: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=900&q=80&auto=format&fit=crop", cap: "Suite induk, balkoni berskrin" },
    ],
    highlights: [
      { n: "01", t: "Pelan taman dahulu", d: "Setiap bilik kediaman membuka ke halaman tengah." },
      { n: "02", t: "Muka jalan tenang", d: "Skrin kayu menghalang matahari barat dan pandangan biasa." },
      { n: "03", t: "Bumbung sedia solar", d: "Titik pemasangan solar PV 8kWp pra-pasang." },
    ],
  },
  u5: {
    id: "u5",
    eyebrow: "Reka & Bina · BINA MAX",
    title: "Binaan Tersuai U5",
    location: "Shah Alam, Selangor",
    year: "2025",
    hero: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=1800&q=80&auto=format&fit=crop",
    lead:
      "Rumah tersuai dua tingkat untuk isi rumah berbilang generasi — sayap berasingan untuk ibu bapa, anak-anak dan tetamu, semuanya dihubungkan oleh halaman bersama.",
    specs: [
      { k: "Pakej", v: "BINA MAX" },
      { k: "Keluasan binaan", v: "2,000 kps" },
      { k: "Jenis", v: "Dua tingkat" },
      { k: "Bilik tidur", v: "5 bilik · 4 mandi" },
      { k: "Tempoh", v: "8 bulan" },
      { k: "Harga", v: "dari RM460,000" },
    ],
    plan: {
      img: "https://images.unsplash.com/photo-1545158539-8f9a7e8b7b8e?w=1400&q=80&auto=format&fit=crop",
      caption: "Susun atur tiga sayap · teras halaman bersama",
    },
    intent:
      "Tiga generasi di bawah satu bumbung memerlukan pemisahan akustik dan visual tanpa rumah terasa berpecah. Halaman menjadi titik tumpu sosial — setiap sayap membacanya secara berbeza dan menggunakannya sebagai limpahan.",
    materials: ["Bata tanah liat dicuci putih", "Pelapis cedar dibakar", "Lantai konkrit digilap", "Perkakas tembaga dihalus", "Panel siling rotan"],
    gallery: [
      { img: "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=900&q=80&auto=format&fit=crop", cap: "Halaman waktu senja" },
      { img: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80&auto=format&fit=crop", cap: "Ruang tamu sayap ibu bapa" },
      { img: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=80&auto=format&fit=crop", cap: "Suite tetamu" },
    ],
    highlights: [
      { n: "01", t: "Pengasingan akustik", d: "Rockwool 50mm antara sayap — kesenyapan tahap bilik tidur." },
      { n: "02", t: "Tingkat bawah reka bentuk universal", d: "Tanpa anak tangga, pintu lebar untuk penuaan setempat." },
      { n: "03", t: "Carport sedia EV", d: "Litar 32A dan konduit pra-tarik ke beranda." },
    ],
  },
  klang: {
    id: "klang",
    eyebrow: "Renovasi",
    title: "Pembaharuan Halaman Moden",
    location: "Klang, Selangor",
    year: "2024",
    hero: "/assets/assets/courtyard renewal.png",
    lead:
      "Teres 1990-an dilucutkan kepada cengkerang dan dibina semula sekitar halaman tengah — tamu terbuka, kehijauan mewah di teras, dan pengatapan semula penuh.",
    specs: [
      { k: "Skop", v: "Renovasi seluruh rumah" },
      { k: "Keluasan binaan", v: "1,800 kps" },
      { k: "Tahun asal", v: "1996" },
      { k: "Bilik tidur", v: "4 bilik · 3 mandi" },
      { k: "Tempoh", v: "4 bulan" },
      { k: "Harga", v: "RM300,000" },
    ],
    plan: {
      img: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1400&q=80&auto=format&fit=crop",
      caption: "Susun atur baharu — dapur ditarik ke depan, tamu dibuka ke sambungan belakang",
    },
    intent:
      "Pelanggan telah membesar daripada susun atur tetapi suka kawasan kejiranan. Kami menanggalkan tiga dinding dalaman, membina semula dapur sebagai jantung sosial, dan menambah pavilion belakang 200 kps yang dibaca sebagai sebahagian daripada asal — bukan tambahan.",
    materials: ["Lantai cengal kitar semula", "Dinding mikrosimen", "Kaunter kuarza", "Perkakas hitam matte", "Bumbung zincalume baharu"],
    gallery: [
      { img: "/assets/assets/courtyard 2.png", cap: "Halaman dalam bersinaran matahari — bumbung polikarbonat, sempadan batu kerikil dan pintu gelongsor ke dapur terbuka" },
      { img: "/assets/assets/courtyard 1.png", cap: "Serambi depan yang direnovasi pada waktu senja — kanopi rata, pintu gelongsor lantai-ke-siling dan pencahayaan skons hitam matte" },
      { img: "/assets/assets/courtyard 7.png", cap: "Dapur kering — kabinet kayu veneer, kaunter kuarza putih dan perkakas hitam matte" },
      { img: "/assets/assets/courtyard 6.png", cap: "Ruang tamu terbuka — lantai kayu kejuruteraan, kipas siling dan pintu gelongsor ke halaman di belakang" },
      { img: "/assets/assets/courtyard 5.png", cap: "Zon tamu — lampu sorot terbenam, skons dinding hitam matte dan dinding putih yang bersih" },
      { img: "/assets/assets/courtyard 4.png", cap: "Fasad depan yang direnovasi — kemasan render putih, kanopi bumbung rata dan pintu utama berpalang menegak hitam" },
      { img: "/assets/assets/courtyard 3.png", cap: "Ruang makan dan dapur dalam pandangan — kipas siling lebar di atas lantai kayu hangat" },
    ],
    highlights: [
      { n: "01", t: "Paip & wayar baharu", d: "Penggantian M&E penuh — waranti 25 tahun." },
      { n: "02", t: "Siling bertebat", d: "Rockwool batt mengurangkan haba atas sebanyak 40%." },
      { n: "03", t: "Fasad belakang dibina semula", d: "Pintu gelongsor 3.6m baharu memenuhi dapur dengan cahaya." },
    ],
  },
  pj: {
    id: "pj",
    eyebrow: "Renovasi",
    title: "Penyegaran Dapur PJ",
    location: "Petaling Jaya, Selangor",
    year: "2025",
    hero: "https://images.unsplash.com/photo-1556909114-44e3e9399a2f?w=1800&q=80&auto=format&fit=crop",
    lead:
      "Reset dapur dan ruang tamu bersebelahan untuk pasangan muda yang memasak setiap malam — aliran kerja lebih baik, cahaya lebih baik, dengan keluasan asal.",
    specs: [
      { k: "Skop", v: "Dapur + tamu" },
      { k: "Kawasan", v: "420 kps gabungan" },
      { k: "Hartanah", v: "Rumah link PJ" },
      { k: "Kabinet", v: "Carcass tersuai" },
      { k: "Tempoh", v: "6 minggu" },
      { k: "Harga", v: "RM200,000" },
    ],
    plan: {
      img: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1400&q=80&auto=format&fit=crop",
      caption: "Dapur galley → aliran kerja island · pass-through ke tamu",
    },
    intent:
      "Dapur galley asal memaksa dua tukang masak melepasi satu sama lain. Kami menanggalkan dinding pembahagi, menggantikannya dengan island 2.4m, dan mendorong rangkaian peralatan ke dinding belakang supaya aliran kerja mengalir dalam satu arah.",
    materials: ["Carcass kabinet birch-ply", "Atas island batu tersinter", "Jubin splashback berkaca tangan", "Perkakas paip tembaga", "Lantai oak engineered"],
    gallery: [
      { img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80&auto=format&fit=crop", cap: "Pandangan island ke makan" },
      { img: "https://images.unsplash.com/photo-1600210491969-aab3a3a8b4a6?w=900&q=80&auto=format&fit=crop", cap: "Rangkaian peralatan + pantri tinggi" },
      { img: "https://images.unsplash.com/photo-1600573472556-e636c2acda88?w=900&q=80&auto=format&fit=crop", cap: "Ruang tamu, sambungan baharu" },
    ],
    highlights: [
      { n: "01", t: "Soft-close untuk semua", d: "Pelari dan engsel Blum, waranti seumur hidup." },
      { n: "02", t: "Geometri dua-tukang", d: "Segitiga dikekalkan di bawah 2.1m di semua stesen." },
      { n: "03", t: "Peralatan tersembunyi", d: "Peti sejuk, mesin basuh pinggan dan ketuhar gelombang mikro bersepadu." },
    ],
  },
  usj: {
    id: "usj",
    eyebrow: "Dalaman · 9-dalam-1",
    title: "Ummi Maktum, Usim",
    location: "USIM, Negeri Sembilan",
    year: "2025",
    hero: "/assets/assets/usim 1.png",
    lead:
      "Pakej dalaman lengkap untuk keluarga muda berpindah ke binaan baharu — lantai, siling, langsir, dapur, almari, cat, lampu, konsol TV dan set makan, semuanya dalam satu kontrak.",
    specs: [
      { k: "Pakej", v: "Dalaman 9-dalam-1" },
      { k: "Liputan", v: "Rumah penuh" },
      { k: "Bilik tidur", v: "4 bilik · 3 mandi" },
      { k: "Item dihantar", v: "9 kategori" },
      { k: "Tempoh", v: "5 minggu" },
      { k: "Harga", v: "RM59,999" },
    ],
    plan: {
      img: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1400&q=80&auto=format&fit=crop",
      caption: "Pelan suasana · asas neutral, sentuhan kayu hangat",
    },
    intent:
      "Pelanggan inginkan rumah yang diselaraskan disampaikan sekali gus — tanpa mengejar lima vendor, tanpa ketidaksamaan tona. Kami menyusun pemasangan supaya mereka berpindah pada hari ke-35 dengan semuanya di tempat, termasuk seni dan gaya.",
    materials: ["Lantai vinil SPC", "Siling cornice plaster", "Langsir roller siang-dan-malam", "Atas dapur kuarza", "Sentuhan rotan asli"],
    gallery: [
      { img: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80&auto=format&fit=crop", cap: "Ruang tamu, siap" },
      { img: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&q=80&auto=format&fit=crop", cap: "Bilik tidur induk" },
      { img: "https://images.unsplash.com/photo-1556909114-44e3e9399a2f?w=900&q=80&auto=format&fit=crop", cap: "Dapur + makan" },
    ],
    highlights: [
      { n: "01", t: "Satu kontrak", d: "Satu PIC, satu jadual, satu kad waranti." },
      { n: "02", t: "Sedia masuk", d: "Linen, peralatan masak dan mentol disertakan." },
      { n: "03", t: "Tahun penjagaan", d: "Lawatan sentuhan 12 bulan disertakan." },
    ],
  },
  kajang: {
    id: "kajang",
    eyebrow: "Reka & Bina · BINA MAX",
    title: "Rumah Halaman Kajang",
    location: "Kajang, Selangor",
    year: "2025",
    hero: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1800&q=80&auto=format&fit=crop",
    lead:
      "Rumah halaman kontemporari di lot bucu — halaman berfungsi dua kali sebagai cerobong cahaya, cerobong pengudaraan dan tempat lepak keluarga.",
    specs: [
      { k: "Pakej", v: "BINA MAX" },
      { k: "Keluasan binaan", v: "2,200 kps" },
      { k: "Jenis", v: "Dua tingkat (lot bucu)" },
      { k: "Bilik tidur", v: "4 bilik · 4 mandi" },
      { k: "Tempoh", v: "9 bulan" },
      { k: "Harga", v: "dari RM520,000" },
    ],
    plan: {
      img: "https://images.unsplash.com/photo-1505691723518-36a5ac3b2d0a?w=1400&q=80&auto=format&fit=crop",
      caption: "Pelan bentuk-C membungkus halaman bertanam 4×4m",
    },
    intent:
      "Pada lot bucu, langkah jelas adalah memenuhi sempadan. Kami melakukan sebaliknya — menarik bangunan ke belakang dan membungkusnya dalam C sekitar halaman terbuka, mendapatkan pengudaraan silang dan memberikan setiap bilik pemandangan hijau.",
    materials: ["Soffit konkrit off-form", "Limewash luaran", "Turapan travertine", "Tingkap keluli hitam", "Pintu jati Burma"],
    gallery: [
      { img: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=900&q=80&auto=format&fit=crop", cap: "Halaman dari ruang tamu" },
      { img: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=900&q=80&auto=format&fit=crop", cap: "Butiran fasad di bucu" },
      { img: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=900&q=80&auto=format&fit=crop", cap: "Ensuite induk" },
    ],
    highlights: [
      { n: "01", t: "Penyejukan pasif", d: "Cerobong halaman menarik udara melalui ruang tamu sepanjang hari." },
      { n: "02", t: "Tuaian air hujan", d: "Tangki 1,500L menyuap taman dan basuh luar." },
      { n: "03", t: "Kaca akustik", d: "Bucu kaca dua-lapis menentang bunyi jalan." },
    ],
  },
  cyber: {
    id: "cyber",
    eyebrow: "Dalaman · 7-dalam-1",
    title: "Loft Cyber",
    location: "Cyberjaya, Selangor",
    year: "2024",
    hero: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1800&q=80&auto=format&fit=crop",
    lead:
      "Pemasangan pangsapuri perkhidmatan untuk profesional muda yang bekerja jauh — zon kerja fleksibel, zon tidur tenang, dapur lapang untuk satu bilik tidur.",
    specs: [
      { k: "Pakej", v: "Dalaman 7-dalam-1" },
      { k: "Keluasan binaan", v: "1,100 kps" },
      { k: "Susun atur", v: "1 bilik · 1 belajar · 1 mandi" },
      { k: "Item dihantar", v: "7 kategori" },
      { k: "Tempoh", v: "3 minggu" },
      { k: "Harga", v: "RM49,999" },
    ],
    plan: {
      img: "https://images.unsplash.com/photo-1556909114-44e3e9399a2f?w=1400&q=80&auto=format&fit=crop",
      caption: "Teras pelan terbuka · zon tidur di belakang sekatan gelongsor",
    },
    intent:
      "Hidup loft tanpa kompromi loft. Sekatan kayu gelongsor menukar satu volum terbuka kepada studio lapang untuk hiburan, atau bilik tidur + ruang belajar berasingan pada waktu malam.",
    materials: ["Lantai oak engineered", "Panel akustik rupa linen", "Dapur keluli dihalus", "Atas kuarza rupa marmar", "Langsir sheer hitam"],
    gallery: [
      { img: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&q=80&auto=format&fit=crop", cap: "Tamu terbuka, sekatan terbuka" },
      { img: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80&auto=format&fit=crop", cap: "Zon tidur, sekatan ditutup" },
      { img: "https://images.unsplash.com/photo-1556909114-44e3e9399a2f?w=900&q=80&auto=format&fit=crop", cap: "Rangkaian dapur padat" },
    ],
    highlights: [
      { n: "01", t: "Sekatan gelongsor", d: "Konfigurasi semula rumah dalam 3 saat." },
      { n: "02", t: "Meja tanpa kabel", d: "Kuasa dalam-meja dan USB-C, tiada wayar kelihatan." },
      { n: "03", t: "Pencahayaan gred hotel", d: "Tiga adegan — kerja, rehat, tidur." },
    ],
  },
  ampang: {
    id: "ampang",
    eyebrow: "Renovasi",
    title: "Refit Ampang",
    location: "Ampang, Selangor",
    year: "2024",
    hero: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1800&q=80&auto=format&fit=crop",
    lead:
      "Refit dua-ruang berfokus — dapur dan bilik mandi induk — untuk pasangan yang inginkan impak tanpa pembinaan semula rumah penuh.",
    specs: [
      { k: "Skop", v: "2 ruang" },
      { k: "Kawasan", v: "Dapur + mandi induk" },
      { k: "Hartanah", v: "Kondominium Ampang" },
      { k: "Gangguan", v: "Renovasi sambil didiami" },
      { k: "Tempoh", v: "4 minggu" },
      { k: "Harga", v: "RM100,000" },
    ],
    plan: {
      img: "https://images.unsplash.com/photo-1600566753051-31bd3d63bb04?w=1400&q=80&auto=format&fit=crop",
      caption: "Pelan semula zon basah — WC dipindah, pancuran walk-in baharu",
    },
    intent:
      "Dua minggu intensif setiap zon, disusun supaya pelanggan tidak pernah kehilangan kedua-duanya. Kami melindungi bilik bersebelahan dengan penghadang habuk penuh dan menjalankan kerja mengikut jadual harian yang ketat — tiada kejutan.",
    materials: ["Lantai + dinding mikrosimen", "Skrin kaca tanpa bingkai", "Perkakas tembaga hitam matte", "Atas vanity kuarza", "Bahagian depan kabinet walnut"],
    gallery: [
      { img: "https://images.unsplash.com/photo-1600573472556-e636c2acda88?w=900&q=80&auto=format&fit=crop", cap: "Rangkaian dapur baharu" },
      { img: "https://images.unsplash.com/photo-1600566753051-31bd3d63bb04?w=900&q=80&auto=format&fit=crop", cap: "Pancuran walk-in" },
      { img: "https://images.unsplash.com/photo-1600210491969-aab3a3a8b4a6?w=900&q=80&auto=format&fit=crop", cap: "Vanity, dua-mangkuk" },
    ],
    highlights: [
      { n: "01", t: "Protokol sambil didiami", d: "Pembersihan harian 5 petang, penghadang habuk, sarung kasut." },
      { n: "02", t: "Sifar bocor", d: "Paip diuji tekanan, waranti basah 10 tahun." },
      { n: "03", t: "Mesra strata", d: "Semua kerja dalam waktu JMB dan peraturan senarai bahan." },
    ],
  },
};

export const MS_CARDS: CardData[] = [
  {
    id: "saujana",
    category: "design-build",
    img: "/assets/assets/house 1.jpg",
    alt: "Rumah setingkat Bandar Saujana",
    location: "Bandar Saujana, Selangor",
    year: "2024",
    title: "Setingkat Saujana",
    priceLine: "BINA START · 1,200 kps · dari RM200,000",
    zoom: true,
  },
  {
    id: "subang",
    category: "design-build",
    img: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80&auto=format&fit=crop",
    alt: "Rumah separuh-dua-tingkat Subang Jaya",
    location: "Subang Jaya, Selangor",
    year: "2024",
    title: "Pavilion Subang",
    priceLine: "BINA PLUS · 1,500 kps · dari RM350,000",
  },
  {
    id: "u5",
    category: "design-build",
    img: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80&auto=format&fit=crop",
    alt: "Rumah dua tingkat Shah Alam",
    location: "Shah Alam, Selangor",
    year: "2025",
    title: "Binaan Tersuai U5",
    priceLine: "BINA MAX · 2,000 kps · dari RM460,000",
  },
  {
    id: "klang",
    category: "renovation",
    img: "/assets/assets/courtyard renewal.png",
    alt: "Renovasi Pembaharuan Halaman Moden",
    location: "Klang, Selangor",
    year: "2024",
    title: "Pembaharuan Halaman Moden",
    priceLine: "Renovasi · 1,800 kps · RM300,000",
  },
  {
    id: "pj",
    category: "renovation",
    img: "https://images.unsplash.com/photo-1556909114-44e3e9399a2f?w=800&q=80&auto=format&fit=crop",
    alt: "Renovasi dapur Petaling Jaya",
    location: "Petaling Jaya, Selangor",
    year: "2025",
    title: "Penyegaran Dapur PJ",
    priceLine: "Renovasi · dapur + ruang tamu · RM200,000",
  },
  {
    id: "usj",
    category: "interior",
    img: "/assets/assets/usim 1.png",
    alt: "Ummi Maktum, Usim dalaman",
    location: "USIM, Negeri Sembilan",
    year: "2025",
    title: "Ummi Maktum, Usim",
    priceLine: "Dalaman 9-dalam-1 · rumah penuh · RM59,999",
  },
  {
    id: "kajang",
    category: "design-build",
    img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80&auto=format&fit=crop",
    alt: "Rumah tersuai Kajang",
    location: "Kajang, Selangor",
    year: "2025",
    title: "Rumah Halaman Kajang",
    priceLine: "BINA MAX · 2,200 kps · dari RM520,000",
  },
  {
    id: "cyber",
    category: "interior",
    img: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    alt: "Pangsapuri Cyberjaya",
    location: "Cyberjaya, Selangor",
    year: "2024",
    title: "Loft Cyber",
    priceLine: "Dalaman 7-dalam-1 · 1,100 kps · RM49,999",
  },
  {
    id: "ampang",
    category: "renovation",
    img: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&q=80&auto=format&fit=crop",
    alt: "Renovasi Ampang",
    location: "Ampang, Selangor",
    year: "2024",
    title: "Refit Ampang",
    priceLine: "Renovasi · 2 ruang · RM100,000",
  },
];

export const MS_FILTER_LABELS = {
  all: "Semua projek",
  designBuild: "Reka & Bina",
  renovation: "Renovasi",
  interior: "Dalaman",
  ariaLabel: "Tapis projek",
  viewProjectLabel: "Lihat projek",
};
